### ISSUE TITLE
How to make sparsity on latent feature vector

### ISSUE THREAD

**Issue by fadying** [comadan/FM_FTRL#1]
``` python
if sign * z_fm[i][k] <= L1_fm:
    w_fm[i][k] = 0.
```

This code can not make remove latent feature vector. 

Do you think `sum(sign * z_fm[i][k]) <= L1_fm then remove` will work?

**Comment by comadan** [comment]
I'm not sure what you mean. Could you elaborate on what you mean by latent feature vector? What are you summing over, `z_fm[i][k]` is a single value? I believe, the L1 regularization should set weights to zero assuming the L1_fm is greater than z. The model should encourage a sparse set of weights.

**Comment by fadying** [comment]
Each feature x has to keep an array `w_fm[i]` of length k. The L1_fm just set one `w_fm[i][k]` to 0. The whole storage would not change. I tried to remove `w_fm[i]` when all the `w_fm[i][k]` is 0, but none is removed.

**Comment by comadan** [comment]
Yes. That is absolutely true, the storage does not efficiently change. However, if you want to create a more storage efficient implementation, I would probably suggest a different approach: e.g. keying the stored weights by a tuple (i, k) and deleting when the L1 constraint is not met. I think you want to implement like this:

```
if sign * z_fm[(i, k)] <= L1_fm:
    del w_fm[(i, k)]
```

However, since during training you have to still retain z, this is probably only a constant multiple change in storage during training. It could be a storage savings during prediction if you only save the components you need for prediction.
